name: 'user-srv'
user-srv:
    ip: '0.0.0.0'
    port: 50001
mysql:
  host: '127.0.0.1'
  port: '3306'
  db: 'mxshop_user_srv'
  user: 'abc'
  password: '123456'
consul:
  host: '127.0.0.1'
  port: '8500'
